name: Build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lista file
        run: |
          dir
          dir /s /b *.cpp

      - name: Compile injector
        run: g++ twks_injector.cpp -o twks_injector.exe -lkernel32 -static -O2

      - name: Compile DLL
        run: g++ -shared twks_executor.cpp -o twks_executor.dll -lkernel32 -static -O2

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: TWKS-Executor
          path: |
            twks_injector.exe
            twks_executor.dll
